<?php

/*
 * This class is generated by jignesh
 * Class to make things easy to manage 
 * Othre stuff that helps to manage perform operations
 */

namespace Mobntouch\APIBundle\Classes;

use Mobntouch\DataBaseBundle\Document\Jobs;

/**
 * Manage other stuffs likes string related operations, change formats etc
 *
 * @author Ved Solution
 */
class ManageJob {

    private $dm;
    private $util;

    function __construct($dm, Container $container = null) {
        $this->dm = $dm;
        $this->util = new Utility();
    }

    public function getApplicantsDetails($job, $limit = 10, $offest = 0) {
        $skip = $limit * $offest;
        
        $applicants = is_object($job) ? $job->getAppliedBy() : $job['appliedBy'];
        
        $applicants = array_splice($applicants, $skip, $limit);

        foreach ($applicants as $key => $applicant) {
            $user = $this->dm->createQueryBuilder('DataBaseBundle:User')
                    ->hydrate(false)
                    ->field('username')->equals($applicant['username'])
                    ->select(array('id', 'username', 'name', 'lastname', 'avatar', 'cover', 'jobTitle', 'city', 'miniResume', 'summary', 'keywords', 'educations', 'experiences'))
                    ->sort('profilePoints', -1)
                    ->getQuery()
                    ->getSingleResult();

            $usersActivityData = $this->dm->createQueryBuilder('DataBaseBundle:UsersActivity')
                    ->hydrate(false)
                    ->select('loginTime')
                    ->field('username')->equals($applicant['username'])
                    ->sort('loginTime', -1)
                    ->getQuery()
                    ->getSingleResult();

            $applicants[$key]['miniResume'] = isset($user['miniResume']) ? $user['miniResume'] : null;
            $applicants[$key]['summary'] = isset($user['summary']) ? $user['summary'] : null;
            $applicants[$key]['keywords'] = isset($user['keywords']) ? $user['keywords'] : null;
            $applicants[$key]['educations'] = isset($user['educations']) ? $user['educations'] : null;
            $applicants[$key]['experiences'] = isset($user['experiences']) ? $user['experiences'] : null;
            $applicants[$key]['date'] = is_object($applicant['date']) ? $applicant['date']->{'value'} : $applicant['date'];
            $applicants[$key]['lastActive'] = $usersActivityData && isset($usersActivityData['loginTime']) ? (string) ($usersActivityData['loginTime'] * 1000 ) : null;
        }

        return $applicants;
    }

}
